export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL';

export const SHOW_ADD_FORM = 'SHOW_ADD_FORM';

export const DELETE_TASK_START = 'DELETE_TASK_START';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAIL = 'DELETE_TASK_FAIL';

export const ADD_TASK_START = 'ADD_TASK_START';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_FAIL = 'ADD_TASK_FAIL';

export const TOGGLE_REMINDER_START = 'TOGGLE_REMINDER_START';
export const TOGGLE_REMINDER_SUCCESS = 'TOGGLE_REMINDER_SUCCESS';
export const TOGGLE_REMINDER_FAIL = 'TOGGLE_REMINDER_FAIL';
